server:
  port: 8000
spring:
  application:
    name: issueMoaGateway
  cloud:
    gateway:
      routes:
        - id: board
          uri: lb://ISSUEMOABOARD
          predicates:
            - Path=/board/**, /board-favorite/**
          filters:
            - ClientAuthFilter
        - id: users
          uri: lb://ISSUEMOAUSERS
          predicates:
            - Path=/users/**
          filters:
            - ClientAuthFilter
        - id: learning
          uri: lb://ISSUEMOALEARNING
          predicates:
            - Path=/interview/**, /voca/**, /voca-learn/**, /grade-exp/**
          filters:
            - ClientAuthFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://61.102.114.235:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /board/v3/api-docs
        name: board
      - url: /users/v3/api-docs
        name: users
      - url: /voca/v3/api-docs
        name: voca