server:
  port: 38000
spring:
  application:
    name: issueMoaGateway
  cloud:
    gateway:
      routes:
        - id: board
          uri: lb://ISSUEMOABOARD
          predicates:
            - Path=/board/**, /board-favorite/**
          filters:
            - ClientAuthFilter
        - id: users
          uri: lb://ISSUEMOAUSERS
          predicates:
            - Path=/users/**
          filters:
            - ClientAuthFilter
        - id: voca
          uri: lb://ISSUEMOAVOCA
          predicates:
            - Path=/voca/**, /voca-learn/**, /grade-exp/**
          filters:
            - ClientAuthFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.23:38761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /board/v3/api-docs
        name: board
      - url: /users/v3/api-docs
        name: users
      - url: /voca/v3/api-docs
        name: voca