server:
  port: 8000
spring:
  application:
    name: issueMoaGateway
  cloud:
    gateway:
      routes:
        - id: board
          uri: lb://ISSUEMOABOARD
          predicates:
            - Path=/board/**, /board-favorite/**
          filters:
            - ClientAuthFilter
        - id: users
          uri: lb://ISSUEMOAUSERS
          predicates:
            - Path=/users/**
          filters:
            - ClientAuthFilter
        - id: voca
          uri: lb://ISSUEMOAVOCA
          predicates:
            - Path=/voca/**, /voca-learn/**, /grade-exp/**
          filters:
            - ClientAuthFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    urls:
      - name: board
        url: http://localhost:8000/board/v3/api-docs