server:
  port: 8000
spring:
  application:
    name: issuemoaUserGateway
  cloud:
    gateway:
      routes:
        - id: support
          uri: lb://ISSUEMOAUSERSUPPORT
          predicates:
            - Path=/support/**
          filters:
            - ClientAuthFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka