server:
  port: 8000
spring:
  application:
    name: issueMoaGateway
  profiles:
    active: docker
  config:
    import:
      - common.yml
eureka:
  client:
    serviceUrl:
      defaultZone: http://issuemoa-eureka:8761/eureka